---
- name: Gather some nextcloud configuration facts
  ansible.builtin.import_tasks: nc_facts.yml
  tags:
    - always
    - facts
- name: Set archive name
  ansible.builtin.set_fact:
    nc_archive_path: "{{ nextcloud_backup_target_dir }}/{{ nc_archive_name }}"
  tags:
    - always
- name: Enter maintenance mode
  ansible.builtin.command: "php {{ nextcloud_webroot }}/occ maintenance:mode --on"
  become_user: "{{ nextcloud_websrv_user }}"
  become: true
  become_method: "{{ ansible_become_method }}"
  become_flags: "{{ ansible_become_flags }}"
  register: __goto_maintenance
  changed_when:
    - __goto_maintenance.stdout | regex_search('already') == none
  tags:
    - always

- name: Run basic backup
  ansible.legacy.import_tasks: files.yml
- name: Run users data backup
  ansible.legacy.import_tasks: user_data.yml
  when: nextcloud_backup_user
- name: Run applications backups
  ansible.legacy.import_tasks: app_data.yml
  when: nextcloud_backup_user
- name: Run batabase backup
  ansible.legacy.import_tasks: database.yml
  when: nextcloud_backup_database
  tags:
    - db_dump
- name: Finish the backup
  ansible.legacy.import_tasks: finishing.yml
