- import_tasks: nc_facts.yml
  tags:
    - always
    - facts
- name: set archive name
  ansible.builtin.set_fact:
    nc_archive_path: "{{ nextcloud_backup_target_dir }}/{{ nc_archive_name }}"
  vars:
    nc_archive_name: >-
      {{ nextcloud_instance_name }}_nextcloud-{{ nc_status.versionstring }}_{{ ansible_date_time.iso8601_basic_short }}{{ nextcloud_backup_suffix }}
  tags:
    - always
- name: enter maintenance mode
  ansible.builtin.command: "php {{ nextcloud_webroot }}/occ maintenance:mode --on"
  become_user: "{{ nextcloud_websrv_user }}"
  become: true
  become_method: su
  become_flags: -s /bin/sh
  register: __goto_maintenance
  changed_when:
    - __goto_maintenance.stdout | regex_search('already') == none
  tags:
    - always

- import_tasks: files.yml
- import_tasks: user_data.yml
  when: nextcloud_backup_user
- import_tasks: app_data.yml
  when: nextcloud_backup_user
- import_tasks: database.yml
  when: nextcloud_backup_database
  tags:
    - db_dump
- import_tasks: finishing.yml
